apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secret-service-account
  namespace: testapp
  annotations:
    azure.workload.identity/client-id: xxxxx # Change
    azure.workload.identity/tenant-id: xxxxx # Change